### ISSUE TITLE
File Handling throws error

### ISSUE THREAD

**Issue by tomayac** [tomayac/fugu-greetings#22]

**Comment by christianliebel** [comment]
Nevermind, this happened due to a wrong MIME type for Web Share Target, the warning is a bit misleading though: https://chromium.googlesource.com/chromium/src/+/refs/heads/master/third_party/blink/renderer/modules/manifest/manifest_parser.cc#732 -- could imagine writing a patch for that 😎

However, we could still verify if File Handling matches the lastest spec.
